GET http://localhost:8000/rest/users

###

GET http://localhost:8000/rest/groups

###

POST http://localhost:8000/rest/groups
Content-Type: application/json

{
  "creatorUserId": 22,
  "groupName": "UK roadtrip",
  "groupAccess": "public"
}

###

POST http://localhost:8000/rest/comments
Content-Type: application/json

{
  "userId": 22,
  "content": "Looking for people to join me on a trip to Finland"
}

###